[package]
name = "ultrahdr"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Safe-ish Rust wrapper around libultrahdr"

[features]
default = ["vendored", "iso21496"]
vendored = ["ultrahdr-sys/vendored"]
shared = ["ultrahdr-sys/shared"]
gles = ["ultrahdr-sys/gles"]
iso21496 = ["ultrahdr-sys/iso21496"]
no-threads = ["ultrahdr-sys/no-threads"]

[dependencies]
ultrahdr-sys = { path = "../ultrahdr-sys" }

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
