[package]
name = "ultrahdr"
version = "0.1.0"
edition = "2021"
description = "Safe-ish Rust wrapper around libultrahdr"
license = "Apache-2.0"

[features]
default = ["vendored", "iso21496"]
vendored = ["ultrahdr-sys/vendored"]
shared = ["ultrahdr-sys/shared"]
gles = ["ultrahdr-sys/gles"]
iso21496 = ["ultrahdr-sys/iso21496"]

[dependencies]
ultrahdr-sys = { path = "../ultrahdr-sys" }

[dev-dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
